#!/bin/sh -e

DATABASE="$SNAP_DATA/db"
mkdir $DATABASE

# start with the sample config
cat > "$DATABASE/target_config.json" << EOF
{
    "follower_1": {
        "protocol": "https",
        "domain": "example.com",
        "port": 3000,
        "gzip": true
    },
    "follower_2": {
        "dsn": "postgresql://example.com:5432",
        "flags": {
            "transaction_isolation": "REPEATABLE-READ",
            "autocommit": true
        }
    },
    "follower_3": {
        "logs": [
            "/var/lib/landscape-client/broker.log",
            "/var/lib/landscape-client/monitor.log",
            "/var/lib/landscape-client/manager.log"
        ]
    },
    "follower_4": {
        "telemetry": true
    }
}
EOF
