name: aspects-registration-agent
base: core22
version: "0.1"
license: GPL-2.0-only
summary: Snap that pulls and applies aspects config.
description: |
  This snap syncs with the registration server to register
  devices and sync configuration.

grade: devel
confinement: devmode

environment:
  ACCOUNT_ID: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN

apps:
  daemon:
    command: bin/registration-agent-cli
    daemon: oneshot
    timer: 00:00-24:00/1440  # every minute
    # commented since snapd-control is a superprivileged plugin that requires
    # manual review by the store, install as devmode
    plugs:
      - network
      # - snapd-control

parts:
  registration-agent:
    plugin: python
    source: .
    parse-info:
      - setup.py
    python-packages:
      - snap-http==1.4.0
      - requests==2.31.0
      - cryptography==42.0.5
