name: aspects-follower
base: core22
version: "0.1"
license: GPL-2.0-only
summary: Snap that consumes aspects config.
description: |
  This snap is functionally empty, it only watches for changes in
  the config and logs them out to stdout.

grade: devel
confinement: devmode

environment:
  ACCOUNT_ID: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN

apps:
  daemon:
    command: bin/follower-cli
    daemon: oneshot
    timer: 00:00-24:00/1440  # every minute
    # commented since snapd-control is a superprivileged plugin that requires
    # manual review by the store, install as devmode
    # plugs:
    #   - snapd-control

parts:
  follower:
    plugin: python
    source: .
    parse-info:
      - setup.py
