name: Lint and Test

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    env:
      GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: make depends && echo $GITHUB_COMMIT_MESSAGE

      - name: Lint & run type checking
        run: make check

      - name: Test
        run: make test
